baseurl = "https://v2less.com"
languageCode = "en-us"
title = "V2Less"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Navi"
    url = "/navi/"
    weight = 3    
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5
#[[menu.main]]
#    name = "Subscribe"
#    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [V2Less](https://v2less.com) 2017 -- 2019 | [Github](https://github.com/sandylaw) | [Twitter](https://twitter.com/v2less)"
